return {
	{
		Name = "Test HvH Demon",
		Author = "test_guy",
		Description = "Full HvH.",
		Version = "1.0",
		Category = "HvH",
		Configuration = [[
{"RageBot_Enabled":{"Value":true,"Type":"Toggle"},"RageBot_Part":{"Value":"Head","Type":"Dropdown"},"RageBot_MultiTarget":{"Value":true,"Type":"Toggle"},"Aimbot_FOVRadius":{"Value":150,"Type":"Slider"},"ESPVisuals_Chams":{"Value":true,"Type":"Toggle"}}
		]],
	},
	{
		Name = "Test Ragecloset",
		Author = "test_girl",
		Description = "Rage visuals testing",
		Version = "1.0",
		Category = "Rage",
		Configuration = [[
{"RageBot_Enabled":{"Value":true,"Type":"Toggle"},"RageBot_Backtrack":{"Value":true,"Type":"Toggle"},"Combat_HitMarkers":{"Value":true,"Type":"Toggle"}}
		]],
	},
	{
		Name = "Test Midground",
		Author = "tester",
		Description = "semi-rage testing",
		Version = "1.0",
		Category = "Semi-Rage",
		Configuration = [[
{"Aimbot_Enabled":{"Value":true,"Type":"Toggle"},"Aimbot_Type":{"Value":"Silent","Type":"Dropdown"},"Aimbot_FOVRadius":{"Value":90,"Type":"Slider"}}
		]],
	},
	{
		Name = "Test Closet",
		Author = "tester",
		Description = "semi-legit testing",
		Version = "1.0",
		Category = "Semi-Legit",
		Configuration = [[
{"Aimbot_Enabled":{"Value":true,"Type":"Toggle"},"Aimbot_Type":{"Value":"Camera","Type":"Dropdown"},"Aimbot_Smoothness":{"Value":8,"Type":"Slider"}}
		]],
	},
	{
		Name = "Test Angel",
		Author = "test_guy",
		Description = "legit testing",
		Version = "1.0",
		Category = "Legit",
		Configuration = [[
{"Aimbot_Enabled":{"Value":true,"Type":"Toggle"},"Aimbot_Type":{"Value":"Mouse","Type":"Dropdown"},"Aimbot_ShowFOV":{"Value":true,"Type":"Toggle"}}
		]],
	},
	{
		Name = "Test Drifter",
		Author = "tester",
		Description = "should show everywhere",
		Version = "1.0",
		Configuration = [[
{"Combat_RadarHack":{"Value":true,"Type":"Toggle"}}
		]],
	},
}
