return {
	{
		Name = "testing hvh",
		Author = "x",
		Description = "omg real hvh no fake",
		Version = "1.0",
		Category = "HvH",
		Configuration = [[
            {"RageBot_Enabled":{"Value":true,"Type":"Toggle"},"RageBot_Part":{"Value":"Head","Type":"Dropdown"},"RageBot_MultiTarget":{"Value":true,"Type":"Toggle"}}
		]],
	},
	{
		Name = "test rage",
		Author = "x",
		Description = "erm akshually hvh is rage :nerd:",
		Version = "1.0",
		Category = "Rage",
		Configuration = [[
            {"RageBot_Enabled":{"Value":true,"Type":"Toggle"},"RageBot_Backtrack":{"Value":true,"Type":"Toggle"},"Combat_HitMarkers":{"Value":true,"Type":"Toggle"}}
		]],
	},
	{
		Name = "wow so legit",
		Author = "x",
		Description = "me no cheater me legit",
		Version = "1.0",
		Category = "Legit",
		Configuration = [[
            {"Aimbot_Enabled":{"Value":true,"Type":"Toggle"},"Aimbot_Type":{"Value":"Mouse","Type":"Dropdown"},"Aimbot_Smoothness":{"Value":8,"Type":"Slider"}}
		]],
	},
	{
		Name = "music box",
		Author = "x",
		Description = "this is not fnaf",
		Version = "1.0",
		Configuration = [[
            {"Combat_RadarHack":{"Value":true,"Type":"Toggle"}}
		]],
	},
}
